import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import HeaderPrincipal from './components/HeaderPrincipal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'StatsKingsFutbol',
  description: 'Generated by create next app',
  icons: {
    icon: '/Logo.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderPrincipal />
        {children}
      </body>
    </html>
  );
}
